services:
  api:
    build: 
      context: ./api
      target: final
    ports:
      - "3000:3000"
    environment:
      DATABASE_CONNECTION_STRING_FILE: /run/secrets/db_connection_string
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      USERNAME: keystone
      USER_PASSWORD_FILE: /run/secrets/user_password
    secrets:
      - db_connection_string
      - jwt_secret
      - user_password
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: keystone
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

secrets:
  db_password:
    file: db_password.txt
  db_connection_string:
    file: db_connection_string.txt
  jwt_secret:
    file: jwt_secret.txt
  user_password:
    file: user_password.txt